name: Call Security CI in Repo A

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  call-reusable:
    # Use @v1 if you tagged Repo A; otherwise @main works too
    uses: saicharank0513-sys/DEV/.github/workflows/security-ci.yml@v1
    permissions:
      contents: read
      actions: read
